spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.travora=DEBUG

google.places.api.key=
google.places.location=1.3521,103.8198
google.places.radius=30000

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

