spring.application.name=backend

spring.datasource.url=jdbc:postgresql://db.dyuhpzxtlcufvnmlrgkj.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Mf421378616j
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect