spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.travora=DEBUG

google.places.api.key=placeholder
google.places.location=1.3521,103.8198
google.places.radius=30000



# # spring.application.name=backend
# # spring.datasource.url=jdbc:postgresql://db.dyuhpzxtlcufvnmlrgkj.supabase.co:5432/postgres?sslmode=require
# # spring.datasource.username=postgres
# # spring.datasource.password=<password>
# # spring.jpa.hibernate.ddl-auto=update
# # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# omar's changes
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.dyuhpzxtlcufvnmlrgkj
spring.datasource.password=<password>
spring.datasource.driver-class-name=org.postgresql.Driver

